// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileUploadError } from "./FileUploadError";
import type { ProjectManagerError } from "./ProjectManagerError";

export type AppError = { InternalError: string } | { ProjectManagerError: ProjectManagerError } | { FileUploadError: FileUploadError };