// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapacitorConfiguration } from "./CapacitorConfiguration";
import type { UpDownType } from "./UpDownType";

export interface AsymmetricIntegrator { up: number, down: number, up_down_type: UpDownType, comparator_enable: boolean, buffer_gm: number | null, capacitor_configuration: CapacitorConfiguration | null, parasitic_capacitance: number | null, unit_capacitance: number | null, }