// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CapacitorConfiguration = "Internal" | "Internal2x" | "Internal3x" | "Internal4x" | "Internal4x_2xS4_S3" | "Internal4x_2xS4_S3_S2" | "Internal4x_S4" | "ParasiticOnly";