// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Parameters } from "./Parameters";
import type { Position } from "./Position";
import type { Terminal } from "./Terminal";

export interface Element { id: bigint, parent_network_id: bigint, type_name: string, element_type_params: Parameters, terminals: Array<Terminal>, position: Position, }