// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { Terminal } from "./Terminal";

export interface ElementVO { id: string, parent_network_id: bigint | null, name: string, type_name: string, element_type_params: Record<string, Record<string, string>>, terminals: Array<Terminal>, position: Position, }