// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileUploadRequest } from "./FileUploadRequest";

export interface FilesUploadRequest { proj_slug: string, input_files: Array<FileUploadRequest>, }