// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Filterbank { band_frequencies: Array<bigint>, quality_factor: Array<number>, attack_rates: Array<number>, decay_rates: Array<number>, }