// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GainOpampMode } from "./GainOpampMode";

export interface GainOpampParams { gain_mode: GainOpampMode, feedback_cap_count: number, }