// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GainOpampMode = "Noninverting1x" | "Noninverting11x" | "Inverting2x" | "Inverting4x" | "Inverting10x" | "Inverting20x";