// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GainOpampMode } from "./GainOpampMode";
import type { OpampType } from "./OpampType";

export interface GainOpAmp { gain_mode: GainOpampMode, opamp_implementation: OpampType, feedback_cap_count: number, }