// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementVO } from "./ElementVO";
import type { Node } from "./Node";

export interface NetworkVO { id: number | null, name: string, elements: Array<ElementVO>, nodes: Array<Node>, creator_id: number, }