// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Node {
	id: string;
	name: string;
	parent_network_id: bigint;
	terminal_ids: Array<string>;
}
