// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcDiffParams } from "./AcDiffParams";
import type { AsymmetricIntegratorParams } from "./AsymmetricIntegratorParams";
import type { ComparatorParams } from "./ComparatorParams";
import type { FilterParams } from "./FilterParams";
import type { FilterbankParams } from "./FilterbankParams";
import type { GainOpampParams } from "./GainOpampParams";
import type { LookupTableParams } from "./LookupTableParams";
import type { MultiplierParams } from "./MultiplierParams";
import type { NeuralNetParams } from "./NeuralNetParams";
import type { PGAParams } from "./PGAParams";
import type { PeakDetectorParams } from "./PeakDetectorParams";
import type { SynthesizedFilterParams } from "./SynthesizedFilterParams";
import type { TerminalParams } from "./TerminalParams";

export type Parameters = { AcDiff: AcDiffParams } | { AsymmetricIntegrator: AsymmetricIntegratorParams } | { Comparator: ComparatorParams } | { Filter: FilterParams } | { Filterbank: FilterbankParams } | { GainOpamp: GainOpampParams } | { LookupTable: LookupTableParams } | "DelayFlipFlop" | { Multiplier: MultiplierParams } | "Mux2" | { NeuralNet: NeuralNetParams } | { PeakDetector: PeakDetectorParams } | { PGA: PGAParams } | { SynthesizedFilter: SynthesizedFilterParams } | { Terminal: TerminalParams };