// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelVersion } from "./ModelVersion";

export interface PeakDetector { atk: number, dec: number, model_version: ModelVersion, }