// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ProjectDetails { id: number, slug: string, name: string, description: string | null, modified_at: DateTime, created_at: DateTime, }