// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkVO } from "./NetworkVO";

export interface SimulateNetworkRequest { network: NetworkVO, project_slug: string, audio_file_path: string, }