// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Network } from "./Network";

export interface SimulateNetworkRequest { network: Network, audio_file_path: string, }