// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SimulatorError = { CommandBuildError: string } | { CommandExecutionError: string } | { JsonParseError: string } | { DirectoryError: string } | { FileError: string } | { SerializationError: string } | { ProjectNotFoundError: string };