// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface TerminalParams { hardware_pin: string | null, is_input: boolean, is_output: boolean, is_ac_coupled: boolean | null, is_extern: boolean | null, }