// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TerminalDirection } from "./TerminalDirection";

export interface TerminalMetadata { description: string, direction: TerminalDirection, default: string | null, dc_range: string | null, ac_range: string | null, }