// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Terminal { id: string, parent_element_id: bigint, type_name: string, node_name: string, }