// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileUploadError =
	| "FileNotFound"
	| "ProcessingError"
	| "FileTooLarge"
	| "UnsupportedFileExtension"
	| { ProjectNotFound: string }
	| { UnableToQueryDatabase: string }
	| { UnableToStoreInDatabase: string }
	| { UnableToDeleteFile: string }
	| { UnauthorizedAccess: string };
