// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileMetadata } from "./FileMetadata";
import type { FileUploadErrorResponse } from "./FileUploadErrorResponse";

export interface FilesUploadResponse {
	upload_success_files: Array<FileMetadata>;
	upload_failed_files: Array<FileUploadErrorResponse>;
	attempted: number;
	succeeded: number;
	failed: number;
}
