// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileUploadError } from "./FileUploadError";

export interface FileUploadErrorResponse {
	file_name: string;
	error_response: FileUploadError;
}
