// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileMetadata } from "./FileMetadata";
import type { FileUploadErrorResponse } from "./FileUploadErrorResponse";

export type FilesUploadResponse = {
	upload_success_files: FileMetadata[];
	upload_failed_files: FileUploadErrorResponse[];
	attempted: number;
	succeeded: number;
	failed: number;
};
