// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilterType } from "./FilterType";

export type Filter = { characteristic_frequency: number, quality_factor: number, filter_type: FilterType, }