// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FilterBank = { band_frequencies: bigint[], quality_factor: number[], attack_rates: number[], decay_rates: number[], }