// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DataSet } from "./DataSet";

export type GetFilesRequest = {
	proj_slug: string;
	dataset_type: DataSet | undefined;
};
