// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Element } from "./Element";
import type { Node } from "./Node";

export interface Network { id: bigint, name: string, elements: Array<Element>, nodes: Array<Node>, creator_id: bigint, }