// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivationFunction } from "./ActivationFunction";

export interface NeuralNet { weights: Array<number>, biases: Array<number>, activation_function: Array<ActivationFunction>, }