// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivationFunction } from "./ActivationFunction";

export type NeuralNet = { weights: number[], biases: number[], activation_function: ActivationFunction[], }