// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AcDiff } from "./AcDiff";
import type { Filter } from "./Filter";
import type { FilterBank } from "./FilterBank";
import type { TerminalParams } from "./TerminalParams";

export type Parameters = { AcDiff: AcDiff } | { Filter: Filter } | { FilterBank: FilterBank } | { Terminal: TerminalParams };