// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TerminalParams = { hardware_pin: string | undefined, is_input: boolean, is_output: boolean, is_ac_coupled: boolean | undefined, is_extern: boolean | undefined, }